### ISSUE TITLE
Seperate Quick Poll experience

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#128]
Suggested by Sass during 7/28/2022

There should be a separate quick poll experience with fewer options which specifically focuses get a poll up in the least number of clicks

We will be streamlining the "create election" page as well, but the "quick poll" page is different as it will be reduced to only support the minimum number of features. Maybe we'd have a prompt on the quick poll page saying "if you want more options, please log in and do click create election"

We can look to the current star.vote experience as an example

Also quick poll should be possible without making an account, whereas users currently don't have access until they make an account

**Comment by mikefranze** [comment]
This is definitely on the list. We'd want 3 different presets for settings with the ability to edit them. One question is if we want users the ability to create a quick poll without creating account, like current star.vote, and how we'd handle that.

**Comment by ArendPeter** [comment]
Yep, that came up during the meeting as well. I think we have 2 broad options

A: If we're planning for star.vote 2.0 to accommodate casual users, then I think quick poll shouldn't require an account, as that would scare most people away

B: If we're planning to keep star.vote available as a place for casual users, and focus star.vote 2.0 toward "serious" elections, then the choice doesn't matter as much

I'm hoping for option A, but that's more of a high level strategy question

**Comment by mikefranze** [comment]
Maybe if the user isn't logged in we could create a random temp ID that is stored in the cookies, then if an election is created and the user isn't logged in we can look for that. We could also use that as an alternative to the IP address voter ID but that could be easily abused.
