### ISSUE TITLE
Make "register" button more obvious

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#131]
Noticed during 7/28/2022 happy hour meeting

Users can register through keycloak, but the button is easy to miss. We should look into updating the user interface, or adding a direct link from the star.vote console

**Comment by mikefranze** [comment]
Is this in keycloak or the react app?

**Comment by ArendPeter** [comment]
It could be either. Here's the 2 approaches

A. Rename login button to "My Account" (or give it a generic profile image), and clean up the keycloak page to make the register option more clear (examples of this approach https://www.pimsleur.com and https://www.yoyogames.com )

B. Separate buttons for login and register directly on the star.vote page (examples of this approach https://forum.yoyogames.com/index.php and https://www.nytimes.com)
We could tweak the visuals of the keycloak page to make the register link more obvious, or if that's not enough we can have a direct register link from the website

We can try option A first since it'll probably be easier, and then switch to B if the UX is still confusing

**Comment by ArendPeter** [comment]
We're probably going to investigate reskinning keycloak (#306) soonish, so we can also investigate this then

**Comment by ArendPeter** [comment]
The wording is better now but still not ideal, I'll resolve this issue in favor of this one:

https://github.com/Equal-Vote/star-server/issues/525
