### ISSUE TITLE
Add live updates to sandbox

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#132]
Suggested by Sass during 7/28/2022 happy hour meeting

For sandbox mode it would be nice if the results were updating as the csv is updated. Currently users need to hit "Get Results" whenever they want the results to refresh

**Comment by mikefranze** [comment]
This would be a good first React issue. Would involve using hooks to run functions when the data changes, checking that the data is valid(don't want to fetch if user is in the middle of typing and the input is not in the right format), and fetching results if valid.
