### ISSUE TITLE
Move configuration files to a shared folder for backend/frontend

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#14]
Several files are shared across frontend and backend

- [ ] Move config files to a shared folder
- [ ] Update frontend/backend build process to pull in any shared files

Specifically we should move the auth configuration here, https://github.com/Equal-Vote/star-server/blob/main/frontend/src/App.tsx#L18

My vote is to use YAML, that way we can have multiple configurations stored for testing, but then comment out the ones we're not using

**Comment by ArendPeter** [comment]
This reddit post has a good overview on the options for handling this

https://www.reddit.com/r/typescript/comments/op0ysp/comment/h62dkmp/?utm_source=share&utm_medium=web2x&context=3

It mentions creating an additional project folder, and then using either lerna, npm packages, or local package dependencies to get everything linked up

I looked into lerna [here](https://www.youtube.com/watch?v=p6qoJ4apCjA). It seems cool, but it's probably overkill for our setup. We'll probably go with the local package dependency option for now, and then possibly move to lerna in the future

**Comment by mikefranze** [comment]
Some of this may be unnecessary, I was able to get the React app to grab files from the domain_model folder, where before it was saying it couldn't grab files outside it's src folder.
