### ISSUE TITLE
Add optional private key as alternate to keycloak token

### ISSUE THREAD

**Issue by mikefranze** [Equal-Vote/star-server#169]
In order to allow users such as discord/slack bots to use our backend we'd need to let them ignore our login system and provide their own key. Any API calls to elections created with this key would require this key to prevent other platforms from accessing this election.

Votes for these elections would include an id for each user, for example the id of a discord user who submits the ballot.

**Comment by scottPlusPlus** [comment]
So theoretically they can provide this (public) key when they create the election, and we can store that key with the election and then if present we should use that key to validate the users.  Clarifying that they would not need to re-send the key with every API call.

Quick overview on validating the signature using RS256 asymmetric keys
https://medium.com/dataseries/public-claims-and-how-to-validate-a-jwt-1d6c81823826

May get a little tricky allowing election-creation with this system.  I suppose we could open the initial election creation to allow users who are signed with a key provided in the election payload itself.
