### ISSUE TITLE
Update ballot instructions to match latest STAR ballot format

### ISSUE THREAD

**Issue by mikefranze** [Equal-Vote/star-server#17]

**Comment by AntonSax** [comment]
The ballot instructions I see are the same as the ballot instructions from an image on this page:
https://www.starvoting.us/paper_ballots

Are those instructions incorrect?

**Comment by ArendPeter** [comment]
Yep, that page is correct (Sara confirmed over slack)

Here's the page that needs updating (I managed to make a typo on the election name, woops)

![image](https://user-images.githubusercontent.com/9289903/150200829-2d4f3593-41c1-4cbc-be88-4db5d4570147.png)

In addition to updating the description with the bulleted format, we also want to change the look of the ballot to better match the paper ballot (although we should probably have a separate issue for that)

Here's the reference ballot from the page

![image](https://user-images.githubusercontent.com/9289903/150201250-a7ab2a92-48c3-4208-bda1-a691468eb67f.png)
