### ISSUE TITLE
Investigate root cause for recent keycloak crashes

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#204]
Keycloak has been crashing a lot. So far we've been fixing this by restarting docker, but this needs to be root caused

**Comment by ArendPeter** [comment]
![image](https://user-images.githubusercontent.com/9289903/209848881-24f3f174-0668-440f-b5c6-5f12e497028f.png)
When this happens the CPU spikes to 100%, and exhausts the credits. Then the keycloak page becomes unresponsive. The recent occurences seem to be December 4th, 16th, and 23th

I ran ``docker logs <container id>`` to see logs. December 5th, and 24th both show a reaper error (no idea of these are the actual cause)

```
2022-12-05 08:08:12,339 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012378: ReaperElement appears to be wedged: com.arjuna.ats.arjuna.coordinator.BasicAction.outputCapturedStackTraces(BasicAction.java:3396)
com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.outputCapturedStackTraces(TwoPhaseCoordinator.java:601)
com.arjuna.ats.arjuna.coordinator.TransactionReaper.doWork(TransactionReaper.java:423)
com.arjuna.ats.internal.arjuna.coordinator.ReaperWorkerThread.run(ReaperWorkerThread.java:78)
```

```
2022-12-24 00:16:16,130 WARN  [com.arjuna.ats.arjuna] (Transaction Reaper) ARJUNA012378: ReaperElement appears to be wedged: java.base@11.0.15/java.util.Calendar.createCalendar(Calendar.java:1691)
java.base@11.0.15/java.util.Calendar.getInstance(Calendar.java:1660)
java.base@11.0.15/java.text.SimpleDateFormat.initializeCalendar(SimpleDateFormat.java:676)
java.base@11.0.15/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:620)
java.base@11.0.15/java.text.SimpleDateFormat.<init>(SimpleDateFormat.java:599)
com.arjuna.ats.arjuna.coordinator.BasicAction.outputCapturedStackTraces(BasicAction.java:3394)
com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.outputCapturedStackTraces(TwoPhaseCoordinator.java:601)
com.arjuna.ats.arjuna.coordinator.TransactionReaper.doWork(TransactionReaper.java:423)
com.arjuna.ats.internal.arjuna.coordinator.ReaperWorkerThread.run(ReaperWorkerThread.java:78)
```

Here's some pages of people hitting similar issues
https://developer.jboss.org/thread/275524
https://community.bonitasoft.com/blog/how-increase-default-xa-transaction-timeout
https://keycloak.discourse.group/t/keycloak-timeout-issue/2309

"ARJUNA012095" seems to be a better search term for the logs, that gives me 12-05, 12-14, 12-15, 12-17, and 12-24

For next steps there are some suggested solutions in those links that we can try

**Comment by evanstucker-hates-2fa** [comment]
I'm happy to help with this. Just schedule some time to screen share and we'll get it solved.

**Comment by evanstucker-hates-2fa** [comment]
First step might be to just give it more resources (CPU and mem) to see if that resolves it. Maybe we could also use https://www.yourkit.com/ to try to figure out what's going on...

**Comment by ArendPeter** [comment]
@evanstucker-hates-2fa @mikefranze 
That sounds great! I'll schedule time with you and Mike soon

**Comment by evanstucker-hates-2fa** [comment]
We found "out of memory" errors in the EC2 instance logs with `journalctl | grep -i "out of mem"`. Seems like 1GB isn't quite enough. We are planning to move this service over to Azure. We can close this issue when we complete that work.

**Comment by ArendPeter** [comment]
We'll need to validate that this issue is fixed after moving keycloak to kubernetes

**Comment by ArendPeter** [comment]
I'm going to resolve this now that we've moved to kubernetes. We can reopen if there's issues there, but right now there isn't anything actionable on this task
