### ISSUE TITLE
Use express-jwt to validate auth tokens on the server side

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#21]
I'm about to post a PR with an oAuth interface. At the moment the backend trusts the tokens that it receives, but we should be validating them using express-jwt https://github.com/auth0/express-jwt

**Comment by ArendPeter** [comment]
This article is also a good reference on JWT validation, https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-verifying-a-jwt.html

It gives an example using the aws-jwt-verify library, we should compare it with express-jwt to see if there are any major differences

**Comment by scottPlusPlus** [comment]
done:  https://github.com/Equal-Vote/star-server/pull/167
