### ISSUE TITLE
New github action to deploy to azure

### ISSUE THREAD

**Issue by mikefranze** [Equal-Vote/star-server#240]

**Comment by evanstucker-hates-2fa** [comment]
This is done.

All code merged to [main branch of star-server](https://github.com/Equal-Vote/star-server) will automatically be deployed to the URL above!

All PRs against [main branch of star-server-infra](https://github.com/Equal-Vote/star-server-infra) (note: -infra) will automatically generate a Terraform plan, which we can review. All code merged to the main branch will automatically be applied. This is dangerous, but powerful. A bad commit to this repo could take down the service - please PR and tag me if you want to make changes in the infra repo.

When you merge code to main on star-server, it runs the [build-push-deploy](https://github.com/Equal-Vote/star-server/actions/workflows/build-push-deploy.yml) GitHub Action that builds, pushes, and deploys a container. The "deploy" part actually does a separate git commit and push directly to main on star-server-infra, which then runs its [tf-plan-apply](https://github.com/Equal-Vote/star-server-infra/actions/workflows/tf-plan-apply.yml) GitHub Action and updates the Azure Container App.

Next steps for me are to fix a security issue and then get the database and Keycloak deployed.

**Comment by evanstucker-hates-2fa** [comment]
Closing
