### ISSUE TITLE
Add support for multi-poll elections

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#25]
Currently our we only support single poll elections, but we should support multi-poll elections at some point (For example, this would allow people to vote for their mayor and their senator on the election)

Our backend already stores the polls as an array, but update the backend logic and the front end to fully support this 

Subtasks
- [ ] Creating/Editing multi-race poll - that will involve reworking the election form.
- [ ] Voting in multi-race poll - that will involve reworking the ballot forms
- [ ] Tabulation - reworking the back end tabulation, might be as simple as a for loop
- [ ] Displaying results - also possibly simple but we should think of how to cleanly do it. Display all winners of each 
election, and allow you to expand for full results maybe?

**Comment by ArendPeter** [comment]
As a part of this issue we'll need to add support for race specific configurations. For example, we want to support elections with choose-one ballot initiatives as well as STAR ballots

**Comment by mikefranze** [comment]
closed in #174
