### ISSUE TITLE
Build and deploy Docker container image

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [Equal-Vote/star-server#260]
We need to add GitHub Action to build and deploy the Docker container image to an Azure image registry.

**Comment by evanstucker-hates-2fa** [comment]
Nevermind, don't deploy to Azure registry. Use ghcr.io instead: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry

It will probably be easier to authentication and work with GitHub's native registry. And hopefully it's free.

**Comment by evanstucker-hates-2fa** [comment]
I think we can basically steal this: https://github.com/actions/starter-workflows/blob/main/deployments/azure-container-webapp.yml

**Comment by evanstucker-hates-2fa** [comment]
Currently failing with this error:
```
buildx failed with: ERROR: failed to solve: failed to push ghcr.io/equal-vote/star-server:0d79c92dd159870040e9d5afa51d27c16d442210: unexpected status: 403 Forbidden
```
I think we need to configurate automatic GITHUB_TOKEN permissions to give it access to write packages. See:
* https://docs.github.com/en/actions/security-guides/automatic-token-authentication
* https://docs.github.com/en/enterprise-cloud@latest/admin/policies/enforcing-policies-for-your-enterprise/enforcing-policies-for-github-actions-in-your-enterprise#configuring-the-default-github_token-permissions

**Comment by mikefranze** [comment]
Fixed with https://github.com/Equal-Vote/star-server/commit/26f5d1f59bf48dec7e2df53173116f74aa84c25d

The build job finishes now but errors on deploy which isn't surprising. 
Error: Deployment Failed, Error: No credentails found. Add an Azure login action before this action. For more details refer https://github.com/azure/login
