### ISSUE TITLE
Add description to create election page

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#28]
When we create elections it would be good to allow for a description box (the backend already supports this, we just need a box on the front end)

You can use [this PR ](https://github.com/Equal-Vote/star-server/pull/26#pullrequestreview-853829713) as a reference

**Comment by AntonSax** [comment]
What is there left to do on this issue?
I can input a description on the New Election page, see the description when selecting from the My Elections page, and see the description on the Election's Ballot page.

**Comment by mikefranze** [comment]
Yea I think this issue is closed now.
