### ISSUE TITLE
Favicon Update

### ISSUE THREAD

**Issue by SaraWolk** [Equal-Vote/star-server#282]
New file attached. It will need to be resized as needed, but this is a full size png verison. It should be the Yellow logo on a black circle background so it looks good in light or dark mode. We've phased out the red star logo. It's too Texas/Communist/Texaco. 

![STAR Voting Favicon](https://github.com/Equal-Vote/star-server/assets/75465271/84d4e70b-cb52-4efb-b9f9-3fbe6a1ecb47)

**Comment by mikefranze** [comment]
Completed with #296
