### ISSUE TITLE
Line spacing

### ISSUE THREAD

**Issue by SaraWolk** [Equal-Vote/star-server#283]
<img width="517" alt="Screenshot 2023-06-04 at 2 03 59 PM" src="https://github.com/Equal-Vote/star-server/assets/75465271/5574be2f-f632-49ab-8956-61c2b89d1b81">

I would add a few more returns to pages like this to space out content chunks more. For example: 

Ballot Submitted
-ballot icon-

Thank you for voting!

["View Results" Button]
["Share Election" Button]
["Donate to the STAR Voting Campaign Fund" Button]

I think the wording above for the buttons is better as well. "Share" could be unclear, are people sharing an "I voted!" type thing on social media? Are they sharing the poll for other voters? 

For the Donate button, this could either be general and just say "Donate", or it could be specific and say a few different things. "Donate to the STAR Voting Campaign Fund". "Donate to STAR Elections" "Donate to Support STAR Voting"

**Comment by mikefranze** [comment]
Completed with #293
