### ISSUE TITLE
Results page funnies

### ISSUE THREAD

**Issue by mikefranze** [Equal-Vote/star-server#291]
Did a quick test and found some issues with new results page, can see here:
https://star-vote-staging.herokuapp.com/Election/7c4a5443-31b2-4212-91df-4d0e02d64475/results

This uses the dev dB for debugging.

First it looks like the names are clipping on the left.
Second, it shows leia and yoda going to the runnoff in the score round but actually leia and luke. This might be due to the fact that the candidate order is not by score but by what order they'd win if you kept running the election.
Third the sections of the pie chart don't line up with the votes in the runoff and chart.

Maybe the fix for this is how we sort the data in the results, or in how it's displayed. Not sure.

![image](https://github.com/Equal-Vote/star-server/assets/41272412/1791e932-9921-4537-9ffa-2b894d98dcca)

![image](https://github.com/Equal-Vote/star-server/assets/41272412/e3d2b6a6-a1e3-4c1c-80e5-756650d2374e)

**Comment by ArendPeter** [comment]
Yep, sorting was a good quick fix in the PR. The PR addresses the other points as well
