### ISSUE TITLE
Address feedback from Brad user test

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#302]
I ran the first user test with Brad (full walkthrough https://youtu.be/Py6hg2jxxy8)

We followed the steps here: https://docs.google.com/document/d/1a63CZ9aQU7JL7Q9IuicBR_bcET0SeFJUmRcg56w45dA/edit

Here's the action items 

Refactor Instruction Pages
- [x] Make instruction image clickable, and vertical (we already knew this, but I'm adding again since it came up)
- [x] Think of ways to show less information on the instruction page (maybe going into detail on how to vote but not how it's counted) (later he gave more feedback https://youtu.be/Py6hg2jxxy8?t=2140 )

Ballot Wording + UX
- [x] #311
- [x] Address feedback on automatic runoff explanation https://youtu.be/Py6hg2jxxy8?t=881
- [x] Address next button confusion https://youtu.be/Py6hg2jxxy8?t=751
- [x] Add no preference info in detailed steps
- [x] Ballot pages are unclear https://youtu.be/Py6hg2jxxy8?t=1193

Results
- [x] Consider including the video in the results, maybe as an added "extra details" section. Because people are much more primed and interested at that point https://youtu.be/Py6hg2jxxy8?t=1011
- [x] Make custom page for single vote elections to avoid complicated tie breakers, https://youtu.be/Py6hg2jxxy8?t=1689

Election Creation UX
- [x] s/Add Bio/Add Details https://youtu.be/Py6hg2jxxy8
- [x] #316
- [x] Make it more clear that you don't need to "remove" candidates (empty boxes default to no candidate) https://www.youtube.com/watch?v=Py6hg2jxxy8
- [x] Consider adding emails to the flow? https://youtu.be/Py6hg2jxxy8?t=3462 (or at least add wording to set an expectation)
- [x] Rename create election button to create draft https://youtu.be/Py6hg2jxxy8?t=3758

Ballot Bug
- [x] Bug with how scores are sorted, https://youtu.be/Py6hg2jxxy8?t=1661

Keycloak
- [x] Fix sign up with google button (or remove)
- [x] ~~Make registration button on keycloak more clear (if possible)~~ I'll handle this as part of the reskin
- [x] #306
- [x] Fix verification email from mike https://youtu.be/Py6hg2jxxy8?t=3070

Election Admin
- [x] Maybe remove filters on empty tables? https://youtu.be/Py6hg2jxxy8?t=3498
- [x] Side panel on admin page is confusing, maybe rename "Home" to "Voting page"? https://youtu.be/Py6hg2jxxy8
- [x] ~~backend crash when hitting finalize election~~ https://youtu.be/Py6hg2jxxy8?t=3604 (this one's probably unsolvable since we don't have logs)

Here are action items specific to the runbook flow
- [x] ~~Change "who should rule the galaxy question" to "who's your favorite character"~~
- [x] ~~Maybe I shouldn't do president vote for recording? then again it's nice having a real world example for the test~~ https://youtu.be/Py6hg2jxxy8?t=1224
- [x] Bullet out scenario 3 to make it easier to follow

**Comment by mikefranze** [comment]
The error with finalizing the election is interesting because the election state did change. What we can do in the future is note the context ID in the error pop up (the part in parentheses) and search for it in the logs to see the what was going on. We'll need to get our logging service set up first or have the heroku logs up during the test.
