### ISSUE TITLE
Address Election Admin feedback from Sara

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#319]
[from sara over slack]

Under the HOME page
 * there is a button for "vote" but the word "vote" is also written in the middle in plain text. (see screenshot)
 * where it says "SHARE" there's no option to share via email. That's available if you click under "Voters", but that might be hard to find or confusing. Maybe under the share drop down there could be an "Add Voters" option that takes you to the add voters page. I know that's redundant, but might be helpful.
 * I'm confused by the Voter Data section and don't get how it works or how I might use it. (see screenshot). I think more context, more instructions, or more info here is needed. Maybe inside the box it could have an example in grey? 1111,[vader@deathstar.com](mailto:vader@deathstar.com),1
 * Is there a way to remove the red spellcheck line from the Voter Data input line?

**Comment by mikefranze** [comment]
I think all this was addressed? Except for disabling spellcheck.
