### ISSUE TITLE
Improve experience of editing elections

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#327]
Adam detailed the issue here: https://docs.google.com/document/d/1NLHLmMb3NOlt7tgtaT0_NZEUCmxDxrC2roGgZiCdHZc/edit

During recent playtests Mike suggested we immediately create a draft the election when you've started the election creation process. This way we can have the election creation flow automatically apply changes, and we can apply the same functionality when editing an existing election

When we do this we'll also want to add feedback that the local changes are in sync with the server

**Comment by mikefranze** [comment]
Been thinking about this. One other feature request is adding a change log to the election. Some potential solutions:

1. Keep current edit election backend route but call it more often. So front end will submit a request to edit the election many times throughout the election creation process whenever a change is made. This would be easy to implement but wouldn't allow tracking. 
2. Change the edit election request payload to be a partial object containing only the changes to made and merge those changes on the backend. For example to change the title the payload would only be election.title = 'new title'. This would allow changes to be tracked as we could just put the payload into a history object in the election. It would also prevent people from overwriting each other if multiple people are editing. The only thing I think would be tough to deal with is the race and candidate arrays as they'd involve indexing. Maybe there's some javascript magic that can do that but I'd be concerned about bugs. 
3. Solution 2 but we create separate routes for adding/deleting/editing races and candidates.

**Comment by mikefranze** [comment]
Closed with #376
