### ISSUE TITLE
Change how we display the logged in user, because people might not want their email displayed

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#331]
Adam detailed the issue here: https://docs.google.com/document/d/1Lnp7x_bdxcGvestKByLBpT8Wklt2VJEkA27Ha8Y6kKo/edit

**Comment by masiarek** [comment]
https://docs.google.com/document/d/1Lnp7x_bdxcGvestKByLBpT8Wklt2VJEkA27Ha8Y6kKo/edit

**Comment by ArendPeter** [comment]
mb, I updated the link in the description

**Comment by ArendPeter** [comment]
use mobile view as reference
