### ISSUE TITLE
Failed to run job on forked repo

### ISSUE THREAD

**Issue by mikefranze** [Equal-Vote/star-server#340]
When committing to main on a forked repo I'm getting emails that the job failed to run 
"[mikefranze/star-server] Run failed: Build, push, and deploy - main"

Is there a way to only run these when committing to Equal-Vote/star-server?

**Comment by ArendPeter** [comment]
Looks like theirs a way to disable github actions on the forked repo

https://github.com/orgs/community/discussions/26704

**Comment by evanstucker-hates-2fa** [comment]
Does @ArendPeter 's solution work for you @mikefranze ? If so, please close this issue.

**Comment by mikefranze** [comment]
Yes it did, forgot to close
