### ISSUE TITLE
Different Winner between Scoring and Runoff: who is the winner (confusing report image), candidates - add quotation marks

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#346]
```Three issues:
Issue 1 - who is the winner? 
- in scoring round -  who is the winner: ‘c’ or ‘a’ - confusing image (report)

Issue 2 - Confusing colors - this maybe 'as designed'
- in scoring round - blue is ‘a’ 
- in runoff  round - blue is ‘c’ 

Issue 3 - suggested improvement - candidates should be in quotation marks
```
https://docs.google.com/document/d/1HxZeTul3PsBdjV2e7Fk8Bq8GGEipk8Tbyt35dTzvGqw/edit

**Comment by mikefranze** [comment]
The "C Wins" is marking the overall winner, the score round is supposed to all be contained in that elevated component. The score round winners should also have stars next to their name to signify that but we've been having issues with the stars getting cropped off.

**Comment by ArendPeter** [comment]
There have been some improvements to this, for example now we swap the 2 front runners if the score order doesn't match the head to head order

![image](https://github.com/Equal-Vote/star-server/assets/9289903/2ae83ee7-3c1b-46a9-aa13-db2d8c102a3f)

That said we're still working on further improvements but I'll close this in favor of #424
