### ISSUE TITLE
Add feature flag support

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#355]
- [ ] Roles: Admins, auditors, credentialers (auditor for example)
 - [ ] Voting methods, one for each
   - [ ] STAR-PR
   - [ ] Ranked-Robin
   - [ ] Approval
   - [ ] Plurality
   - [ ] Ranked Choice
 - [ ] Candidate Details
 - [ ] Multi Race Support
 - [ ] Multi Winner Support

**Comment by evanstucker-hates-2fa** [comment]
Check out https://github.com/Unleash/unleash

**Comment by ArendPeter** [comment]
I look into unleash and other tools a bit, but I think they're overkill for what we need. Most tools focus on release management, a/b testing, and the ability to remotely enable/disable

Here's how I see our phases

* **Phase 1: Environment Variables**: For now I'm thinking we just use environment variables. Developers can override it when they're working on the new features, but we don't set it to TRUE in production until we're ready to release the feature

* **Phase 2: Cache**: If it gets annoying doing code updates for the toggles, it might also be nice to override it using cache variables. We can add that on if needed

* **Phase 3: Service/Library**: When we need a bigger service we can upgrade to unleash or another tool

**Comment by ArendPeter** [comment]
PR here: https://github.com/Equal-Vote/star-server/pull/364
