### ISSUE TITLE
4 winners - reporting

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#359]
Sass indicates that our reporting is incorrect: See details below at: https://docs.google.com/document/d/10_oqicRSItmMOkAzDKfiycANFPPSQbffmrLe9GB1raw/edit

**Comment by mikefranze** [comment]
Can you be more specific? This is the same doc as the other recent issue and I don't see anything about incorrect reporting.

**Comment by mikefranze** [comment]
Closing until more details added
