### ISSUE TITLE
incorrect result - B wins (correct result A wins)

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#367]
incorrect result - B wins (correct result A wins)
    A,B,C,D
21: 5,4,3,2
12: 2,3,5,4
5:  3,2,4,5
12: 3,5,2,4

See details at: https://docs.google.com/document/d/1qNzGzW4gRdQ7_vtGJqBgWknmgfp8dANMc3tmfhh-B-0/edit

**Comment by mikefranze** [comment]
Seems to be an issue with how the sandbox tool parses spaces. Good find, should be an easy fix. 

This input gives correct results

21:5,4,3,2
12:2,3,5,4
5:3,2,4,5
12:3,5,2,4
