### ISSUE TITLE
Improve onboarding flow

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#425]
Here's some improvements that came up when onboarding Jon

https://equal-vote.github.io/star-server/contributions/1_local_setup.html

- [x] Onboarding documentation still has some references to the script it was copied from (which was here: https://contribute.freecodecamp.org/#/how-to-setup-freecodecamp-locally )
- [x] Fix the start script (either update the documentation to show npm run start, or fix npm run dev)
- [x] Make it more clear that credentials are required
- [x] Add instructions for hosting the database locally (and add instructions as needed, but also create scripts where possible)
- [x] Add calendar links, and explain weekly vs monthly meetings: starvoting.us/calendar
- [x] Add instructions for copying frontend sample.env (or update the dev script to copy sample.env to .env when .env isn't present)

**Comment by JonBlauvelt** [comment]
Created slack workflow for onbaording.

**Comment by ArendPeter** [comment]
I've added myself

I'll take a look at the database instructions, I think that's the only task left on here

**Comment by ArendPeter** [comment]
spin up docker image locally

**Comment by ArendPeter** [comment]
Assigning to Mike since he has more context on the database stuff
