### ISSUE TITLE
Allow admins to specify voter authentication on public elections (currently it defaults to ip locked)

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#461]
see parent issue: #449

**Comment by ArendPeter** [comment]
![image](https://github.com/Equal-Vote/star-server/assets/9289903/2856ab80-2dcc-4617-be26-33dffd06e780)
Here's an ugly mock up of what I'm visualizing. This will only be shown for elections that don't rely on a voter list (i.e. those that answered no on the 3rd question of the election creation flow). The settings that need to be modified already exist at election.settings.voter_authentication

**Comment by evanstucker-hates-2fa** [comment]
I think we should definitely default this to NOT be IP locked. I was at a conference recently, and I created a poll. Many of the voters were unable to cast their ballots because we were all on shared wifi...

**Comment by mikefranze** [comment]
Going to tackle this this weekend.

**Comment by ArendPeter** [comment]
In addition the updating the admin view, I wonder if we should have a pop-up for ip vs device id when people are making quick polls?

I'm nervous about having either as a default so I think a quick prompt makes sense

**Comment by mikefranze** [comment]
If the user is logged in, should we use the user id instead of device id? I'm thinking no.

**Comment by mikefranze** [comment]
Actually it looks like currently the auth service code doesn't provide the user temp id if they're logged in, so it'd have to be the user id.
