### ISSUE TITLE
Quick poll - without candidates - missing error message

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#465]
Quick poll can be created without ANY candidates - we should have error message - at least 1 candidate (2 candidates?) should be included.

Video link: https://youtu.be/DSJMu-aXfU8

Screenshot: https://docs.google.com/document/d/11yoAifyZrskAc8MgRREVqtXTBonAQAADH4Fu_fdPnO4/edit

**Comment by ArendPeter** [comment]
We should add validation that there's at least 2 candidates

**Comment by ArendPeter** [comment]
This was resolved by the new backend validation
