### ISSUE TITLE
Usability issue - add candidates - missing warning

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#476]
How to reproduce, add candidate A, B
<img width="321" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/2a166b88-882d-4390-ac4b-bf30329227e9">

Then add candidate "C"

Now click on "Save"

As-Is:
System ignores the last candidate “C” - there is warning/error.

Should-be:
either 
- save the candidate “C” 
- or 
- warn that C will be lost (Dear user - click on button “Add”)

Link to doc:
https://docs.google.com/document/d/1R-qvnSC_YqjmlNUB-DOTBa_GFoHVkpJ1faQ397nN_m8/edit

**Comment by ArendPeter** [comment]
Here are the tasks for this issue

- [ ] Remove add button from candidate creation flow (it should work the same as quick poll on the front page)
- [ ] Hide edit button based on the CANDIDATE_DETAILS feature flag
- [ ] Allow candidate names to be edited without requiring the edit flag
- [ ] Add auto scroll to the bottom of the window (you can reuse the scrolling logic from the details section of the results page)
