### ISSUE TITLE
Error "Invalid Datetime" - Create a Quick Poll with a Registration - test variant "Duplicate a Poll" 

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#477]
Create a Quick Poll with a Registration - duplicate - "Invalid Datetime"

https://docs.google.com/document/d/1mvMBa7xc-zAOGQPrTCvXfWKG5ZqBQDZqJWCeIdmyti8/edit

<img width="818" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/cde7dae6-a084-46c6-8bbb-4c144a6807f3">

Video:
https://youtu.be/sf0EE04za3s

**Comment by mikefranze** [comment]
fixed in #628
