### ISSUE TITLE
Elections / polls without Election Title

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#483]
How to reproduce:
1) Click on New Election (do not enter anything)
2) Navigate away without saving (e.g. click on STAR Vote 2.0 button 
3) Go list of elections - you have a new election without title - empty shell

What is expected:
Navigating away without saving - should 
- trigger a warning message "You will lose your changes - confirm to delete (archive? - this will keep lots of garbage in archived election)
or 
- if nothing populated on the election screen - just ignore the transaction (do not store empty shell in database)

<img width="1231" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/495e39da-5d20-4734-a66a-3eef071c4ef8">

**Comment by ArendPeter** [comment]
This has been resolved with the new election creation flow
