### ISSUE TITLE
Donations link is not working

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#484]
How to reproduce video: https://youtu.be/Sfo79iynd6s

Donation link is not working:
<img width="797" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/24dafd25-f790-4618-96c5-573a514b4411">

<img width="848" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/951c908c-4a55-4c9b-8d2e-acda19c6d63f">

**Comment by ArendPeter** [comment]
Good catch!

I went ahead and assigned this one to you since I think it will be a good first issue

We need to update the link to point to https://www.equal.vote/donate instead

**Comment by masiarek** [comment]
Second change - change the wording:

"Click here" is probably not the best wording...
<img width="960" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/bc269483-0313-4d59-a3bd-1cc030c1759f">

**Comment by ArendPeter** [comment]
Maybe we can try this?

[Donations](https://www.equal.vote/donate) are the best way to support our work

**Comment by ArendPeter** [comment]
Let's also update the donate button in the screenshot to use the equal vote donate link instead of the eugene one

![image](https://github.com/Equal-Vote/star-server/assets/9289903/df2c3a03-b3b4-4836-99bf-56694b195541)

**Comment by masiarek** [comment]
After change:
<img width="396" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/7297e294-61a4-47e6-a06e-236b1df0af26">
