### ISSUE TITLE
Urgent: pre-beta testing Phase - temporarily deactivate "I have read the instructions from “Active” to “Inactive” 

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#489]
Change the default checkbox from “Active” to “Inactive”
<img width="1284" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/9ec92138-8f3d-43f1-8571-18166e1b62aa">

https://docs.google.com/document/d/1UDVnfqFR99txy9-CJzUA_ZInXyGY1Mw3ej1v75VfpOA/edit

We are going to revert the check box to “Active” during the “Go-Live” - version 1.0

**Comment by masiarek** [comment]
Just for testing (it is easier for testing) - temporary change - only in the first 3 weeks of March.
We flip it back in the last week of March.
I fully agree it should be normally active!

**Comment by ArendPeter** [comment]
Cool,  I'll assign this one to you as another good first issue then :)

**Comment by masiarek** [comment]
We have a solution for testers - https://github.com/phenixcoder/feature-flags-chrome-plugin - so maybe we can close this ticket.

**Comment by ArendPeter** [comment]
Agreed, let's close this one
