### ISSUE TITLE
My Election invitations - menu item - remove

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#490]
Typically folks will not register at our website - hence I suggest that we remove this menu item.

Voters will simply use their Notifications (email, SMS, etc) to cast a vote.

<img width="373" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/07d603bc-3acf-420b-aa97-046af7744b8a">

We obviously need a very mature and feature rich “Dashboard” with statuses related to “sent emails” monitoring - what is in the queue, what bounced back, etc - but this is a different concept and approach.

In case we decide to keep - we need to fix the bug:
- video 1 - https://youtu.be/S_GYVQ55wBA
- video 2 - https://youtu.be/zxOXvQektso

**Comment by ArendPeter** [comment]
That's fair, maybe we can disable it with a feature flag, and then add it back when it becomes more relevant

This is another good first issue, the implementation would be very similar to my PR here: https://github.com/Equal-Vote/star-server/pull/466/files

We can work through it in a meeting
