### ISSUE TITLE
Urgent: pre-beta testing Phase - Checkbox “Randomize Candidate Order” - from ‘true to ‘false’ - change the default value

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#491]
Change the default from ’true’ to ‘false’.

Other websites use a default setting for Randomize Candidate Order as “False” - inactive (a fixed order of candidates by default).

<img width="1186" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/befd5bdf-f20c-4bbb-aa26-f9e0d3820d2b">

https://docs.google.com/document/d/1NPK821QliRFhzaUiOpDF2ybzkeHY53y_0y0aM3Bh5mo/edit

**Comment by ArendPeter** [comment]
I feel that randomized should be the default since it avoids any inherit bias towards candidates on the top of the list

I'm not sure why other websites have it default to false. Any ideas?

**Comment by masiarek** [comment]
Just for testing (it is easier for testing - you do not have to pay attention which row is candidate on that you are looking for - reproducible results when testing) - it would be temporary change - only in the first 3 weeks of March.
We are going to flip it back in the last week of March.
I personally think that the default should be off - but this is only a default - users can always change it - authough we are missing a function that after hitting Finalize button - we get a confirmation pop-up window with the election configuration settings to confirm "all is well" - yes, I am OK to finalize.  

Why other website have different default (fixed order of candidates)  - see the answer in green color: https://docs.google.com/document/d/1NPK821QliRFhzaUiOpDF2ybzkeHY53y_0y0aM3Bh5mo/edit

**Comment by ArendPeter** [comment]
We now have feature flags exposed to the front end so we can close this one

https://equal-vote.github.io/star-server/help/99_how_to_enable_beta_features.html
