### ISSUE TITLE
Add new field "Vote Type” with two values "Test" and "Live" to the Election database 

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#492]
Vote Type drives large number of subsequent functions / functionalities / features:
- how to report on elections status (am I in a test mode ot this is a production mode)
- how verification is performed on election with “Live” status:
- user must accept terms
- free vs fee based 

Live mode requires thorough verification of all activities 
- Did the user test ballot display? Are all races included?
- Are correct voting methods selected for each race? 
- Did you try using the ballot to test it? Small number of voters should receive a final email and verify all is well.
- Are all emails imported? 
- Security features implemented (ballot ID vs email ID, etc)
- Is it free or fee based election? Payment received?

<img width="735" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/a804b2ec-7a5e-41ec-b491-00719cb30e87">

See more:
- https://docs.google.com/document/d/1PKkWRbZt5BAr44mSqjvLJSvxNne87iF2KzWe_aqEf-I/edit
- https://docs.google.com/document/d/1EvLN8c7rPV_7lWpabsZEKSlqjlJr12p9ggx2YqFoeNc/edit
- https://docs.google.com/document/d/1xd4MrCkj_Bi8ViJGqzM_IWAPBLVbHylG8BfxbmuJS50/edit

**Comment by ArendPeter** [comment]
Good idea! I can definitely see how having access to the entire flow prior to having the live election is useful for users (especially if it's a larger organization and there's a lot of people/testers who are giving approval)

That said, we can achieve similar functionality now by having them duplicate the election, rename it to TEST, and then add their testers to the duplicate election. I think it's worth polishing this flow further in the future, but for now I think this is going to be a bit further out so I'll update the milestone accordingly

**Comment by mikefranze** [comment]
test votes added in #619
