### ISSUE TITLE
Reporting/dashboard - sort elections and in a Consecutive Sequence 

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#494]
Sort elections and in a Consecutive Sequence 

As is:
Current sorting is by Election Title 
<img width="608" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/5398167a-62e9-4fbc-becb-3fea538662c3">

Should Be:
- add possibility to "Sort elections in a Consecutive Sequence".
 
We are missing Election “Consecutive Number” - instead we have Election random number (UUID): 
Example Election UUID = b7f2afae-6b3c-4630-aef0-72cb0c73457f 

Proposed solutions - should-be:

Option 1 - add Election Consecutive Number (preferred solution)
Add election ID - to be used internally only by election administrators 
(Election Admin can see and use Election consecutive number)
Election Consecutive number (plus election name) is used in reports, dashboards 
External communications - still use Election UUID (random number)
PROS: user friendly number 
CONS: database schema change
See cross reference issue https://github.com/Equal-Vote/star-server/issues/495  

Option 2 - use UUID ver 7 (instead of UUID ver 4 - completely random number)
use UUID - version 7 - time stamp is used as a sorting key (sorting is possible)

Option 3 - sort by Election creation date (field ‘create_date’)
This is easiest solution - maybe good enough for ver 0.1
PROS: no changes to database schema

https://docs.google.com/document/d/10C8JNb4tBoz4bxaOeKl0XuCs8K4o9K1zxm22oMkpKE8/edit

**Comment by mikefranze** [comment]
Added sort by last updated date in #628
