### ISSUE TITLE
Race name not unique (low priority)

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#503]
race name not unique - are we ok with this?

Low priority ...

We can have two races with the same title:

https://dev.star.vote/Election/6774012d-d161-49b1-9552-bf965600c681/admin
<img width="387" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/90736909-10cc-4fc9-8f57-1b77b556e3bd">

**Comment by ArendPeter** [comment]
Resolved in this PR
https://github.com/Equal-Vote/star-server/pull/648
