### ISSUE TITLE
Update tie breaker warning message

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#513]
https://starvoting.slack.com/archives/C014VH2PR6K/p1709692313433129?thread_ts=1709170742.784379&cid=C014VH2PR6K

> Sara: Yeah, the yellow tie warning seems a bit alarming for a scenario where it's really not a tie. I think that should maybe be reserved for true ties only and not be a part of the note.
For the wording I have a few suggestions:
(Remove yellow triangle from note)
"Ties are broken using the Official Tiebreaker Protocol whenever possible.
Ties are 10 times less likely to occur with STAR Voting than with Choose-One Voting and generally resolve as the number of voters increases."
In the event of a true tie, not able to be broken by the protocols, we could have it say "^ The election is currently tied. The tie may resolve if more votes are cast." what do you think?

> Arend: Thanks, I'll update the warning message
I split tie breakers into 3 groups
Tie breakers that can be inferred from the results (i.e. a tie in the runoff, but then it's broken by their scores)
Ties breakers that can't be inferred from the results, but still rely on the data (i.e. a 5-star tie breaker) 
Truely random tie breakers
For scenario 1, we can remove the warning, and just do "Candidate X wins" as the title for the results (but the user can still see the tie breaker by looking at the details)
For scenario 2, we would include the warning, and do "Tied (candidate x won tie breaker)" as the title for the results
For scenario 3, we include the warning, but the title would display this differently depending on if the admin enabled the "break ties randomly" setting for the election. If they want ties broken randomly then the title would be "Tied (candidate x won random tie breaker)", otherwise it'll just show "Tied"
So this is the same as your recommendation, except that I think the warning should also be displayed for scenario 2, since the tie is broken using information that the user can't see

**Comment by ArendPeter** [comment]
posted as screenshot so it's easier to read, sara gave thumbs up so let's move forward with this one

![Image](https://github.com/Equal-Vote/star-server/assets/9289903/98a50b2b-543a-44be-95f5-43c4470c7136)

**Comment by masiarek** [comment]
What should happen in a three-way tie: https://docs.google.com/document/d/1cfSHuu-RbZ2NuOGz934XDktRlrCdfwal52BpKc6YB6o/edit

**Comment by ArendPeter** [comment]
Here's some more formatting tweaks we should add 

![image](https://github.com/Equal-Vote/star-server/assets/9289903/807466cc-13b7-4039-8706-625d0750046b)

**Comment by ArendPeter** [comment]
@masiarek 

> What should happen in a three-way tie: https://docs.google.com/document/d/1cfSHuu-RbZ2NuOGz934XDktRlrCdfwal52BpKc6YB6o/edit

The scenario you mentioned in the document would be a true tie, but to your point it currently randomly selects winners in the scoring round and then the runoff round shows a seemingly clear winner. We might abort the runoff round in this case and just call is a true tie, but it's really tricky. I'll think about it more
