### ISSUE TITLE
Section "Detailed Steps" - add a link to "https://www.starvoting.org/no_preference"

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#520]
"Equal preference" aka "No preference votes"  - these are new concepts - folks need an explanation...

Suggestion - add a link to 
https://www.starvoting.org/equal_preference

Link to document: https://docs.google.com/document/d/1dkNDjIDVbvRVSGtz-UzP3D5D90jnDJSBuK_XIOMRHok/edit

<img width="642" alt="image" src="https://github.com/Equal-Vote/star-server/assets/857777/afe8cd42-42f9-473a-bd6b-d3ad81754577">

**Comment by ArendPeter** [comment]
Hi, we are going through some re-architecting and our setup documentation needs to be updated. Here's the current process for running the server

```
(from the root star-server directory)
npm i -ws
npm build -w shared
npm run dev -ws backend
(moved to separate commmand line tab)
npm run dev -ws frontend
```

That said we're going to merge a PR in the next day or 2 that tweaks the steps again and also updates the documentation, so stay tuned for that https://github.com/Equal-Vote/star-server/pull/527

**Comment by ArendPeter** [comment]
@RahalBhupathi We've merged the PR and updated our docs: https://equal-vote.github.io/star-server/contributions/1_local_setup.html#step-3-install-dependencies-and-start-the-starvote-client-application-and-api-server

It might be easier to delete the repo and reclone since we made some pretty major changes to the file structure

**Comment by ArendPeter** [comment]
To clarify the issue, "Equal Preference votes" is the proper term. We recently decided to switch from No Preference to Equal Preference. So for this task we need to update the wording to equal preference as well as add a hyperlink to https://www.starvoting.org/equal_preference
