### ISSUE TITLE
When there's only 1 vote, don't display winner

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#528]
https://dev.star.vote/Election/80f2cecf-92dc-47f5-8c84-d556cddaa0d5/results

![image](https://github.com/Equal-Vote/star-server/assets/857777/2bee6995-9a52-4140-9557-d3ad0d53fbc9)

![image](https://github.com/Equal-Vote/star-server/assets/857777/54ad5b87-89cf-4e29-a01d-12ee4ec59cd7)

**Comment by ArendPeter** [comment]
Moving to 1.0 since it's a clear bug

**Comment by ArendPeter** [comment]
If there's only 1 vote we probably shouldn't display the winner at all

**Comment by ArendPeter** [comment]
Also created this issue: https://github.com/Equal-Vote/star-server/issues/552

**Comment by ArendPeter** [comment]
https://github.com/Equal-Vote/star-server/issues/465
