### ISSUE TITLE
Add support for uploading candidate photos

### ISSUE THREAD

**Issue by mikefranze** [Equal-Vote/star-server#53]
Ballot has spot for candidate photo but is set to empty profile picture and election database has field for candidate photo filenames. Front end needs to be updated so users can upload a photo and render the photos on the ballot based on filename, backend needs to store photos.

**Comment by ArendPeter** [comment]
This is mildly related but Keycloak can be setup to store user avatars (see 19:50 in this video https://www.youtube.com/watch?v=duawSV69LDI)

That example is for importing the avatar from a linked github account, we'll probably want to have support for avatars via a linked account or allowing them to upload their own pictures to our server

Down the road, we could also allow users to be specified as candidates, in which case we'd retrieve their avatar for the candidate photo

**Comment by ArendPeter** [comment]
This was also suggested by Annie during the 7/28/2022 Happy Hour meeting
