### ISSUE TITLE
Implement public elections tab

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#545]
This can be viewable here: https://dev.star.vote/OpenElections , but it's no longer included as a tab by default. 

We need to update the backend query to only show elections where the is_public flag is set, and then we can enable the tab again

Hint: follow setups at https://equal-vote.github.io/star-server/help/99_how_to_enable_beta_features.html to enable the public elections tab while testing

**Comment by Jeetch8** [comment]
I want to resolve this issue. Can you please assign it to me?

**Comment by ArendPeter** [comment]
Sure thing, I appreciate your interest!

I'll keep an eye on this thread in case you have any questions

**Comment by ArendPeter** [comment]
I recommend following the onboarding instructions here: https://equal-vote.github.io/star-server/contributions/1_local_setup.html

and also be sure to request access to the [credentials document](https://docs.google.com/document/d/1D4CJ9l6lnR39YYPUvw_HbeUVXNR-tAbNF6eT89oxEuk/edit#heading=h.wn1hgmz7g4dg), you'll need that for testing

**Comment by Jeetch8** [comment]
Hii can you please grant me the access to credentials document

**Comment by ArendPeter** [comment]
Hi, did you request access? I might have missed it

But if you're comfortable sharing your email you can also send that to me and I'll grant you access that way

**Comment by Jeetch8** [comment]
jchawda332@gmail.com my email

**Comment by ArendPeter** [comment]
Awesome, I shared it with you. Thank you for bearing with me on this

**Comment by Jeetch8** [comment]
Sir I have question. Can I modify the query itself (adding where(is_public=true)) or should i apply some logic in the controller to only grab elections with the flag?

**Comment by ArendPeter** [comment]
Feel free to modify the query

**Comment by Jeetch8** [comment]
Hii Sir
I have raised the PR. But i am unsure if that is exactly what you needed. Can you please give me feedback? (if possible)

**Comment by ArendPeter** [comment]
Thanks for opening a PR! I left some feedback
