### ISSUE TITLE
Polish the emails

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#584]

**Comment by mikefranze** [comment]
Any specifics?

**Comment by masiarek** [comment]
https://github.com/Equal-Vote/star-server/issues/625

**Comment by ArendPeter** [comment]
My intention when making this issue was to polish the content of the emails received by the voters

One of the feedbacks we got was that the emails weren't very searchable in their inbox. It would also be great to have graphics (once we have the name / logo finalized), and also use buttons instead of a hyperlink

Here's an example email I got from opa vote. I'm not sure how much of the text was written by the election admin, or how much is part of the opa vote template
![image](https://github.com/user-attachments/assets/786b0e55-ed34-4dfc-b20a-f51ba25748a4)

**Comment by mikefranze** [comment]
Header image 
Add more text to give context to election
Add voting begins and ends in email
