### ISSUE TITLE
Convert front page election stats to websocket

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#593]
- only if polling becomes an issue
 - it might not work with a load balancer
 - socket.io

**Comment by mikefranze** [comment]
Example of how to set up websockets https://github.com/Equal-Vote/star-server/commit/e5b5102b7f948d7c2b10a4c8d03c45b2722e9661

Would probably want to convert backend part to middleware or something

**Comment by mikefranze** [comment]
Info on load balancers and Kubernetes here https://socket.io/docs/v4/using-multiple-nodes/

**Comment by mikefranze** [comment]
If we ever need socket io rooms with multiple servers https://socket.io/docs/v4/redis-adapter/
