### ISSUE TITLE
Error making request: 401: Can't view voter roll for open elections (13d73ff9)

### ISSUE THREAD

**Issue by evanstucker-hates-2fa** [Equal-Vote/star-server#597]
I see when when I try to view voters here: https://dev.star.vote/68v4mg/admin/voters

I don't any of the voters in this election registered - they were likely all anonymous - I just shared the election link with them.

**Comment by mikefranze** [comment]
What kind of election was it? If it was open access and you shared a link then I don't think you can view the voters. So I think the issue is that there was a visible option to view the voters when you shouldn't be able to, but that should be an open issue right already.

**Comment by ArendPeter** [comment]
Yeah sounds like it's related to the following

https://github.com/Equal-Vote/star-server/issues/560
