### ISSUE TITLE
Allow for voting during draft mode & add warning on the ballots that the votes will be reset

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#608]

**Comment by mikefranze** [comment]
Was looking at this, ballots have a status field that isn't really used for anything. During draft mode we could set that status to "test" and allow it to be submitted but add a filter the the ballots we use for tabulation after draft phase.

**Comment by ArendPeter** [comment]
That sounds like a good long term solution

Short term I was assume we'd have a API for "clearAllBallots" and we'd call once we hit finalize, as well as everytime candidates are added during draft mode.

This would also allow us to support this feature before adding support for live editing
