### ISSUE TITLE
Donations link is not working

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#610]
https://dev.star.vote/Election/68m34r  - the “donations” link is not working

**Comment by masiarek** [comment]
Video: https://youtu.be/fdabKrW3tp0

**Comment by mikefranze** [comment]
Issue is in the footer, not specific to this poll.

**Comment by masiarek** [comment]
We fixed this in the past twice - yet the issue is reappearing - what is going on?
This is priority issue (donations!) ...

Previous tickets:
https://github.com/Equal-Vote/star-server/issues/523
https://github.com/Equal-Vote/star-server/issues/484
