### ISSUE TITLE
Missing invite email to participate in the election 

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#631]
I created an election with emails - https://dev.star.vote/bfpr76

I did not receive any email invite to any of the emails:
<img width="974" alt="image" src="https://github.com/user-attachments/assets/4e153e8f-374e-4b21-a816-6d3bc884f10b">

**Comment by ArendPeter** [comment]
The emails should be sent out once you hit finalize. Has the election been finalized?

**Comment by mikefranze** [comment]
Election was finalized, fix in #633.
