### ISSUE TITLE
Download ballots - add election ID

### ISSUE THREAD

**Issue by masiarek** [Equal-Vote/star-server#632]
As Is:
ballot_id,a,b,c,d
a16315ff-068a-46bc-85cb-145529e032f4,0,0,0,0
09f24fdc-c7fa-4b3a-a5cd-40764589d17e,0,0,0,0
9c91811b-b4ba-4fad-9ab1-05ef74920a24,0,0,0,0

Should be:
https://dev.star.vote/x3kbxk/admin/ballots

ballot_id,a,b,c,d
a16315ff-068a-46bc-85cb-145529e032f4,0,0,0,0
09f24fdc-c7fa-4b3a-a5cd-40764589d17e,0,0,0,0
9c91811b-b4ba-4fad-9ab1-05ef74920a24,0,0,0,0

**Comment by ArendPeter** [comment]
Could you clarify? I think those blocks are the same, and I can't access the link

**Comment by masiarek** [comment]
The new - the different line is - at the top of the ballot download: https://dev.star.vote/x3kbxk/admin/ballots

**Comment by ArendPeter** [comment]
ah I see

I adding a line at the top of the CSV could make it harder to use the file in a spreadsheet editor, but perhaps we can include the election id in the file name

**Comment by masiarek** [comment]
yes - this is a better approach - add election ID to the file name (CSV download).
