### ISSUE TITLE
Results Page Layout + Anonymized Ballot Download

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#663]
Here's a couple of improvements to make to the results page

- [ ] **Remove race dropdowns**: Currently multi race elections have a separate dropdown for each race. Mark F. , suggested that it would be cleaner if we removed those and I agree. Let's have the races be fully expanded, wither the paper wrapper component removed and separated by ``<hr>`` tags (but keep the existing details dropdowns)
- [ ]  **Calls to action**: At the bottom we should have buttons for "Download Anonymized CSV", "Share Poll/Election" and "Donate" (see thanks page for reference, Share should only be shown on public elections)
- [ ] **Download CSV Setting**: Currently download CSV is only available to admins under the ballot view, but I think it's best practice to have this also shared with voters. This should be a setting that admins can disable, but it should be enabled by default
- [ ] **CSV Bug**: Currently the CSV only displays a single race, but it should include all races. This allows researchers to correlate votes across races. I'm not sure if there's a standard for representing header hierarchies, but "<race name>!!<candidate name>" is a pattern I've seen before

**Comment by csamuele** [comment]
example election https://dev.star.vote/tcvc7r/results
