### ISSUE TITLE
"Get voter auth, isn't authorized and hasn't voted" tests don't pass in isolation

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#74]
In PR #73 , the "Get voter auth, isn't authorized and hasn't voted" tests started failing, but I couldn't find any related changes

After going back to a previous commit (8403b50255887cadc3ba831ab1af5920850c2ca2), I realized that the test passed when all tests were ran but it didn't pass when ran individually

```
npm test -- -t "Get voter auth, isn't authorized and hasn't voted"
```

In particular, the test assumes that the mock database has already been populated, but it hasn't

**Comment by mikefranze** [comment]
Interesting, the mocks should be getting reset after each test. I probably missed populating it and the mock not getting reset didn't cause the test to fail.

**Comment by ArendPeter** [comment]
Resolving, I'm assuming this was fixed?
