### ISSUE TITLE
Review Open Source Services

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#88]
Discussed during our 4/18/22 software-dev meeting

We need to have our design/services reviewed to make sure our design is sufficient for the service to be used by open source organizations. Our code is fully open source on github, but we're also using (or considering) additional services and we want 

Here's the services we're using or considering
* **Source Control**: git hosted on Github
* **Hosting**: Heroku (has containers for KeyCloak, and the main server, and it also hosts postgres databases)
* **Email Server**: SendGrid or Postalserver.io (used for email verification, and to send email invites)
* **Identity Server**: KeyCloak 

Here are the particular questions we had
 * Regarding email, we think SendGrid will be easier to setup, but it's not open source. That said, it's not involved in the tabulation process so we thought it might still be ok to use from an election security perspective?
 * Regarding Heroku, it's not open source, but I'm not sure if there are any open source providers out there. If Heroku isn't an option, would open source organizations prefer self host using our server implementation?
 * If Heroku is an option, how do we validate to the public that we're actually running the same code that's shown in our GitHub?

**Comment by starvoting** [comment]
We are going to meet with Aaron and Pen about the open sourced considerations today at 10am Pacific. Sorry for the short notice. You all are welcome to join if you’re free.
>   https://meet.jit.si/STAR-open-source-meeting-01

**Comment by penyuan** [comment]
> * Regarding email, we think SendGrid will be easier to setup, but it's not open source. That said, it's not involved in the tabulation process so we thought it might still be ok to use from an election security perspective?

Does SendGrid basically provide an SMTP server that you talk to to send emails? Or does it do more than that?

> Regarding Heroku, it's not open source, but I'm not sure if there are any open source providers out there. If Heroku isn't an option, would open source organizations prefer self host using our server implementation?

As I understand it, we are deploying built container images to Heroku, right? If so, I suspect it's fine, because if it is a problem for someone, they can either self-host the image or host it on another platform that they're fine with.

**Comment by ArendPeter** [comment]
The meeting went well, and we determined we're overall pretty compliant

Aside from that the design has changed a bunch since then so this issue isn't super relevant anymore

(although we are reviewing our open source licenses here: https://github.com/Equal-Vote/star-server/pull/475 )
