### ISSUE TITLE
Represent election state as an enum

### ISSUE THREAD

**Issue by ArendPeter** [Equal-Vote/star-server#96]
This will help clean up our code a bit

Here are the tasks
- [ ] Update the database to use enums: https://www.postgresql.org/docs/current/datatype-enum.html
- [ ] Add a customer parser to pg to parse the postgres enums into typescript: https://github.com/brianc/node-pg-types https://www.typescriptlang.org/docs/handbook/enums.html

Sidenotes
* pg supports a lot of built in types, but enum isn't one of them
* typescript supports enums, even though javascript doesn't really https://www.typescriptlang.org/docs/handbook/enums.html
https://www.sohamkamani.com/javascript/enums/

**Comment by mikefranze** [comment]
I think these days the preferred practice is to use typescript string literal types which is what we're now doing
